name: PRrr Prrr

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Overwrite README.md with latest timestamp
        run: |
          echo "Last automatic update trigger: $(date)" > README.md

      - name: Commit and Push Changes
        run: |
          git add README.md
          git diff --quiet --cached || git commit -m "Automated README update to trigger deploy"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
